name: Scheduled Jobs
'on':
  schedule:
    - cron: 0 21 6 1 1
    - cron: 0 20 7 1 2
    - cron: 0 17 14 1 2
    - cron: 0 16 15 1 3
jobs:
  helper-ping-eCTF-Info-Meeting-at-2025-01-06T210000000Z:
    name: helper ping eCTF Info Meeting at 2025-01-06T21:00:00.000Z
    if: github.event.schedule == '0 21 6 1 1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEAmNjgzNDQ5NzI0MjQxNTc1OTUxPgoqKmVDVEYgSW5mbyBNZWV0aW5nKiogaXMgPHQ6MTczNjI4MzYwMDpSPiEKaHR0cHM6Ly9zaWdwd255LmNvbS9tZWV0aW5ncy9lbWJlZGRlZC8yMDI1LTAxLTA3Lw==
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
  helper-ping-eCTF-Info-Meeting-at-2025-01-07T200000000Z:
    name: helper ping eCTF Info Meeting at 2025-01-07T20:00:00.000Z
    if: github.event.schedule == '0 20 7 1 2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEAmNjgzNDQ5NzI0MjQxNTc1OTUxPgoqKmVDVEYgSW5mbyBNZWV0aW5nKiogaXMgPHQ6MTczNjI4MzYwMDpSPiEKaHR0cHM6Ly9zaWdwd255LmNvbS9tZWV0aW5ncy9lbWJlZGRlZC8yMDI1LTAxLTA3Lw==
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
  helper-ping-eCTF-Kickoff-at-2025-01-14T170000000Z:
    name: helper ping eCTF Kickoff at 2025-01-14T17:00:00.000Z
    if: github.event.schedule == '0 17 14 1 2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEAmNjgzNDQ5NzI0MjQxNTc1OTUxPgoqKmVDVEYgS2lja29mZioqIGlzIDx0OjE3MzY5NjA0MDA6Uj4hCmh0dHBzOi8vc2lncHdueS5jb20vbWVldGluZ3MvZW1iZWRkZWQvMjAyNS0wMS0xNS8=
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
  helper-ping-eCTF-Kickoff-at-2025-01-15T160000000Z:
    name: helper ping eCTF Kickoff at 2025-01-15T16:00:00.000Z
    if: github.event.schedule == '0 16 15 1 3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEAmNjgzNDQ5NzI0MjQxNTc1OTUxPgoqKmVDVEYgS2lja29mZioqIGlzIDx0OjE3MzY5NjA0MDA6Uj4hCmh0dHBzOi8vc2lncHdueS5jb20vbWVldGluZ3MvZW1iZWRkZWQvMjAyNS0wMS0xNS8=
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
