name: Scheduled Jobs
'on':
  schedule:
    - cron: 0 16 15 10 2
    - cron: 0 15 16 10 3
jobs:
  helper-ping-Hivestorm-2024at-2024-10-15T160000000Z:
    name: helper ping Hivestorm 2024at 2024-10-15T16:00:00.000Z
    if: github.event.schedule == '0 16 15 10 2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEAmNjgzNDQ5NzI0MjQxNTc1OTUxPgoqKkhpdmVzdG9ybSAyMDI0KiogaXMgPHQ6MTcyOTA5NDQwMDpSPiEKaHR0cHM6Ly9zaWdwd255LmNvbS9tZWV0aW5ncy9wdXJwbGUvMjAyNC0xMC0xNi8=
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
  helper-ping-Hivestorm-2024at-2024-10-16T150000000Z:
    name: helper ping Hivestorm 2024at 2024-10-16T15:00:00.000Z
    if: github.event.schedule == '0 15 16 10 3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEAmNjgzNDQ5NzI0MjQxNTc1OTUxPgoqKkhpdmVzdG9ybSAyMDI0KiogaXMgPHQ6MTcyOTA5NDQwMDpSPiEKaHR0cHM6Ly9zaWdwd255LmNvbS9tZWV0aW5ncy9wdXJwbGUvMjAyNC0xMC0xNi8=
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
