name: Scheduled Jobs
'on':
  schedule:
    - cron: 0 19 5 10 6
    - cron: 0 18 6 10 0
    - cron: 0 16 15 10 2
    - cron: 0 15 16 10 3
jobs:
  helper-ping-Hivestorm-2024at-2024-10-15T160000000Z:
    name: helper ping Hivestorm 2024at 2024-10-15T16:00:00.000Z
    if: github.event.schedule == '0 16 15 10 2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEA2ODM0NDk3MjQyNDE1NzU5NTE+CioqSGl2ZXN0b3JtIDIwMjQqKiBpcyA8dDoxNzI5MDk0NDAwOlI+IQpodHRwczovL3NpZ3B3bnkuY29tL21lZXRpbmdzL3B1cnBsZS8yMDI0LTEwLTE2Lw==
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
  helper-ping-Hivestorm-2024at-2024-10-16T150000000Z:
    name: helper ping Hivestorm 2024at 2024-10-16T15:00:00.000Z
    if: github.event.schedule == '0 15 16 10 3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEA2ODM0NDk3MjQyNDE1NzU5NTE+CioqSGl2ZXN0b3JtIDIwMjQqKiBpcyA8dDoxNzI5MDk0NDAwOlI+IQpodHRwczovL3NpZ3B3bnkuY29tL21lZXRpbmdzL3B1cnBsZS8yMDI0LTEwLTE2Lw==
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
  helper-ping-x86-64-Assemblyat-2024-10-05T190000000Z:
    name: helper ping x86-64 Assemblyat 2024-10-05T19:00:00.000Z
    if: github.event.schedule == '0 19 5 10 6'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEA2ODM0NDk3MjQyNDE1NzU5NTE+CioqeDg2LTY0IEFzc2VtYmx5KiogaXMgPHQ6MTcyODI0MTIwMDpSPiEKaHR0cHM6Ly9zaWdwd255LmNvbS9tZWV0aW5ncy9nZW5lcmFsLzIwMjQtMTAtMDYv
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
  helper-ping-x86-64-Assemblyat-2024-10-06T180000000Z:
    name: helper ping x86-64 Assemblyat 2024-10-06T18:00:00.000Z
    if: github.event.schedule == '0 18 6 10 0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
        working-directory: sigpwny.com
      - env:
          DISCORD_B64_MESSAGE: PEA2ODM0NDk3MjQyNDE1NzU5NTE+CioqeDg2LTY0IEFzc2VtYmx5KiogaXMgPHQ6MTcyODI0MTIwMDpSPiEKaHR0cHM6Ly9zaWdwd255LmNvbS9tZWV0aW5ncy9nZW5lcmFsLzIwMjQtMTAtMDYv
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CONTENT_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: touch .env && npm run send-discord-ping
        working-directory: sigpwny.com
